import networkx as nx


def get_fixed_graph():
    graph = nx.Graph()
    graph.add_edge('A', 'B')
    graph.add_edge('A', 'C')
    graph.add_edge('B', 'D')
    graph.add_edge('C', 'D')
    graph.add_edge('D', 'R')
    graph.add_edge('R', 'Q')
    graph.add_edge('T', 'Q')
    graph.add_edge('I', 'T')
    graph.add_edge('H', 'I')
    graph.add_edge('H', 'J')
    graph.add_edge('J', 'K')
    graph.add_edge('K', 'I')
    graph.add_edge('Q', 'U')
    graph.add_edge('U', 'L')
    graph.add_edge('L', 'M')
    graph.add_edge('L', 'N')
    graph.add_edge('N', 'O')
    graph.add_edge('P', 'O')
    graph.add_edge('N', 'P')
    graph.add_edge('M', 'O')
    graph.add_edge('Q', 'S')
    graph.add_edge('S', 'G')
    graph.add_edge('G', 'F')
    graph.add_edge('F', 'E')
    graph.add_edge('E', 'G')
    return graph


def get_fixed_num_graph():
    graph = nx.Graph()
    graph.add_edge('0', '1')
    graph.add_edge('0', '2')
    graph.add_edge('1', '3')
    graph.add_edge('2', '3')
    graph.add_edge('3', '17')
    graph.add_edge('17', '16')
    graph.add_edge('19', '16')
    graph.add_edge('8', '19')
    graph.add_edge('9', '8')
    graph.add_edge('7', '9')
    graph.add_edge('9', '10')
    graph.add_edge('10', '8')
    graph.add_edge('16', '20')
    graph.add_edge('20', '11')
    graph.add_edge('11', '12')
    graph.add_edge('11', '13')
    graph.add_edge('13', '14')
    graph.add_edge('15', '14')
    graph.add_edge('13', '15')
    graph.add_edge('12', '14')
    graph.add_edge('16', '18')
    graph.add_edge('18', '6')
    graph.add_edge('6', '5')
    graph.add_edge('5', '4')
    graph.add_edge('4', '6')
    graph.add_edge('0', '10')
    return graph
